import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import MainLayout from "../components/layout/main-layout/MainLayout";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>👨🏽‍💻Daniel Cruz - Porfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
      </Head>
      <MainLayout>
        <h1>
          Hola este es mi portfolio, espero que puedas darle un vistazo y puedas
          darme feedback al respecto
        </h1>
        <Link href="/profile">
          <a>Ir al perfil</a>
        </Link>
      </MainLayout>
      <footer></footer>
    </div>
  );
};

export default Home;
